export enum UnidenCommandType {
  GetModelInfo = "MDL",
  GetFirmwareVersion = "VER",
  // PushKey = "KEY",
  // QuickSearchHold = "QSH",
  // GetCurrentStatus = "STS",
  // JumpNumberTag = "JNT",
  // Next = "NXT",
  // Previous = "PRV",
  // FavoritesListQuickKeyStatus = "FQK",
  // SystemQuickKeyStatus = "SQK",
  // DepartmentQuickKeyStatus = "DQK",
  // PushScannerInfo = "PSI",
  GetScannerInfo = "GSI",
  // GetAny = "GLT",
  // Hold = "HLD",
  // SetAvoid = "AVD",
  // ServiceTypeSettings = "SVC",
  // JumpMode = "JPM",
  // GetSetDateAndTime = "DTM",
  // GetSetLocationAndRange = "LCR",
  // AnalyzeStart = "AST",
  // AnalyzePauseResume = "APR",
  UserRecordControl = "URC",
  // MenuMode = "MNU",
  // MenuStatusInfo ="MSI",
  // MenuSetValue = "MSV",
  // MenuStructureBack = "MSB",
  EnterProgramMode = "PRG",
  ExitProgramMode = "ERG",
  CreateSystem = "CSY",
  GetSystemInfo = "SIN",
  SetSystemInfo = "SIN",

}